
source 'https://rubygems.org'

# gem 'activerecord'
# gem 'sinatra-activerecord'
# gem 'rake'
# gem 'require_all'
# gem 'sqlite3', '~> 1.3.6'
# gem 'pry'
# gem 'rest-client'
# gem 'tty-font'
# gem 'progress_bar'
# gem 'tty-prompt'
# gem 'pastel'
# gem 'terminal-table'



gem "sinatra-activerecord"
gem 'sqlite3', '~> 1.3.6'
gem "pry"
gem "require_all"
gem "rest-client"
gem "json"
gem "rake"
gem 'tty-prompt'
gem 'terminal-table'
gem 'tty-font'
gem 'progress_bar'
gem 'pastel'